repos:
  -   repo: local
      hooks:
        - id: pip-compile
          name: pip-compile
          description: Automatically compile requirements.
          entry: pip-compile
          language: python
          files: ^requirements\.(in|txt)$
          pass_filenames: false
        - id: pytest-check
          name: pytest-check
          description: Run unit tests
          entry: pytest
          language: system
          pass_filenames: false
          always_run: true
        - id: mypy
          name: mypy
          entry: mypy
          language: python
          types: [python]
          require_serial: true
          additional_dependencies: ["types-all"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [ --fix ]
        stages: [commit]
        always_run: true
  - repo:  https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        stages: [commit]
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11