repos:
  -   repo: local
      hooks:
        - id: pip-compile
          name: pip-compile
          description: Automatically compile requirements.
          entry: pip-compile
          language: python
          files: ^requirements\.(in|txt)$
          pass_filenames: false
        - id: pytest-check
          name: pytest-check
          description: Run unit tests
          entry: pytest
          language: system
          pass_filenames: false
          always_run: true
        - id: mypy
          name: mypy
          entry: mypy
          language: python
          types: [python]
          require_serial: true
          additional_dependencies: ["types-all"]
        - id: safety-check
          name: safety
          entry: safety check
          language: python
          pass_filenames: false
          always_run: true
        - id: bandit
          name: bandit
          entry: bandit
          language: python
          types: [python]
          args: ["-c", "pyproject.toml", "-r"]
        - id: ruff
          name: ruff
          entry: ruff check
          language: python
          types: [python]
          args: ["--fix"]
          stages: [commit]
        - id: black
          name: black
          entry: black
          language: python
          types: [python]
          stages: [commit]